### ISSUE TITLE
Misuses of cryptographic APIs

### ISSUE THREAD

**Issue by mhp0rtal** [jbossas/patch-gen#24]
Hi
The following lines have cryptographic API misuses. <br> File name => patch-gen/src/main/java/org/jboss/as/patching/generator/JarDiffUtils.java: Line number => 75: API name => MessageDigest:First parameter (with value "SHA1") should be any of {SHA-256, SHA-384, SHA-512}<BR> File name => patch-gen/src/main/java/org/jboss/as/patching/generator/ModuleDiffUtils.java: Line number => 53: API name => MessageDigest:Operation on object of type java.security.MessageDigest object not completed. Expected call to digest, update<BR> File name => patch-gen/src/main/java/org/jboss/as/patching/generator/JarDiffUtils.java: Line number => 77: API name => MessageDigest:<BR> File name => patch-gen/src/main/java/org/jboss/as/patching/generator/ModuleDiffUtils.java: Line number => 94: API name => MessageDigest:<BR> File name => patch-gen/src/main/java/org/jboss/as/patching/generator/JarDiffUtils.java: Line number => 90: API name => MessageDigest:Operation on object of type java.security.MessageDigest object not completed. Expected call to <java.security.MessageDigest: byte[] digest(byte[])>, update<BR>

**Comment by bstansberry** [comment]
Closing; this appears to be a machine generated issue, one of hundred of such issues generated from this github account and the information in it is not clearly useful.
