### ISSUE TITLE
Provide a Maven plug-in

### ISSUE THREAD

**Issue by gunnarmorling** [jbossas/patch-gen#7]
Hi, I've been experimenting with creating a patch file allowing to update Hibernate Validator used within WildFly to the latest and greatest. You can find my experiment here: https://github.com/hibernate/hibernate-validator/pull/572.

Overall things worked out ok, but the biggest issue was the lack of a Maven plug-in for using the patch-gen tool. Hence my question is would you accept a pull request for creating such plug-in - or better yet ;) - create such a plug-in on your end? I think it could be done quite quickly.

Assuming there was a plug-in, it should also be deployed to Maven central so it gets easily usable in builds of projects such as Hibernate Validator.

Thanks a lot for considering this request!

**Comment by aloubyansky** [comment]
Hi @gunnarmorling, I think I would accept it. Thanks!

**Comment by gunnarmorling** [comment]
Hi @aloubyansky, I've sent a PR for the plug-in here: https://github.com/jbossas/patch-gen/pull/8.
